theme: jekyll-theme-cayman
title: Multilevel Text Alignment
show_downloads: "true"
github:
  repository_url: https://github.com/XuhuiZhou/CDA
  zip_url: https://zenodo.org/record/4281569#.X7dAj2hKjLY
